[package]
name = "maohuoban-recommendation-infrastructure"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
maohuoban-recommendation-application.workspace = true
maohuoban-recommendation-domain.workspace = true
sqlx.workspace = true
uuid.workspace = true
