[package]
name = "maohuoban-samecity-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
chrono.workspace = true
maohuoban-samecity-application.workspace = true
maohuoban-samecity-domain.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[lints]
workspace = true
