[package]
name = "maohuoban-pet-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum = { workspace = true, features = ["multipart"] }
chrono.workspace = true
maohuoban-auth-application.workspace = true
maohuoban-auth-domain.workspace = true
maohuoban-auth-http.workspace = true
maohuoban-media-storage.workspace = true
maohuoban-pet-application.workspace = true
maohuoban-pet-domain.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[lints]
workspace = true
