[package]
name = "maohuoban-pet-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
base64.workspace = true
chrono.workspace = true
maohuoban-pet-application.workspace = true
maohuoban-pet-domain.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[lints]
workspace = true
