[package]
name = "maohuoban-profile-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
maohuoban-profile-application.workspace = true
maohuoban-profile-domain.workspace = true
sqlx.workspace = true
uuid.workspace = true

[lints]
workspace = true
