[package]
name = "maohuoban-legal-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
maohuoban-legal-application.workspace = true
maohuoban-legal-domain.workspace = true
sqlx.workspace = true

[lints]
workspace = true
