[package]
name = "maohuoban-ai-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-stream.workspace = true
async-trait.workspace = true
chrono.workspace = true
futures-util.workspace = true
maohuoban-ai-application.workspace = true
maohuoban-ai-domain.workspace = true
maohuoban_diagnostics.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
httpmock.workspace = true
tokio.workspace = true
tower.workspace = true

[lints]
workspace = true
