[package]
name = "maohuoban-pet-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
maohuoban_diagnostics.workspace = true
maohuoban-media-storage.workspace = true
maohuoban-pet-domain.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile = "3.27.0"

[lints]
workspace = true
