#[derive(Debug, Clone, Copy)]
pub enum PetErrorKind {
    Species,
    Sex,
    NeuterStatus,
    BackgroundMediaKind,
    MediaUsageKind,
    MediaAssetStatus,
    MediaBindingStatus,
    MediaDerivativeKind,
    MediaAssetComponentKind,
    ManagedStatus,
    SourceKind,
    LifeStatus,
    OriginKind,
    IdentifierType,
    VerifiedStatus,
    IdentifierStatus,
    GuardianType,
    GuardianRole,
    GuardianStatus,
    LifecycleEventKind,
    EventKind,
    Visibility,
}
